#!/usr/bin/env bash
# -*- coding: utf-8; mode: sh indent-tabs-mode: nil -*-
# SPDX-License-Identifier: GNU General Public License v3.0 or later

# just a simple ./suite "$@" wrapper
sudo -H \
     "FORCE_TIMEOUT=$FORCE_TIMEOUT" \
     "LXC_ENV=$LXC_ENV" \
     "LXC_SUITE_IMAGE=$LXC_SUITE_IMAGE" \
     "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"/suite \
     "$(basename "${BASH_SOURCE[0]}")" "$@"
